# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Config.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Config_Dialog(object):
    def setupUi(self, Config_Dialog):
        Config_Dialog.setObjectName("Config_Dialog")
        Config_Dialog.resize(1030, 756)
        self.buttonBox = QtWidgets.QDialogButtonBox(Config_Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(650, 680, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.listView_2 = QtWidgets.QListView(Config_Dialog)
        self.listView_2.setGeometry(QtCore.QRect(430, 190, 181, 331))
        self.listView_2.setObjectName("listView_2")
        self.listView_3 = QtWidgets.QListView(Config_Dialog)
        self.listView_3.setGeometry(QtCore.QRect(750, 190, 181, 331))
        self.listView_3.setObjectName("listView_3")
        self.pB_add1 = QtWidgets.QPushButton(Config_Dialog)
        self.pB_add1.setGeometry(QtCore.QRect(220, 550, 75, 23))
        self.pB_add1.setObjectName("pB_add1")
        self.pB_add2 = QtWidgets.QPushButton(Config_Dialog)
        self.pB_add2.setGeometry(QtCore.QRect(540, 550, 75, 23))
        self.pB_add2.setObjectName("pB_add2")
        self.pB_add3 = QtWidgets.QPushButton(Config_Dialog)
        self.pB_add3.setGeometry(QtCore.QRect(860, 550, 75, 23))
        self.pB_add3.setObjectName("pB_add3")
        self.label = QtWidgets.QLabel(Config_Dialog)
        self.label.setGeometry(QtCore.QRect(110, 120, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Config_Dialog)
        self.label_2.setGeometry(QtCore.QRect(420, 120, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Config_Dialog)
        self.label_3.setGeometry(QtCore.QRect(740, 120, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Config_Dialog)
        self.label_4.setGeometry(QtCore.QRect(70, 30, 921, 71))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(28)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pB_delete1 = QtWidgets.QPushButton(Config_Dialog)
        self.pB_delete1.setGeometry(QtCore.QRect(220, 590, 75, 23))
        self.pB_delete1.setObjectName("pB_delete1")
        self.pB_delete2 = QtWidgets.QPushButton(Config_Dialog)
        self.pB_delete2.setGeometry(QtCore.QRect(540, 590, 75, 23))
        self.pB_delete2.setObjectName("pB_delete2")
        self.pB_delete3 = QtWidgets.QPushButton(Config_Dialog)
        self.pB_delete3.setGeometry(QtCore.QRect(860, 590, 75, 23))
        self.pB_delete3.setObjectName("pB_delete3")
        self.treeView = QtWidgets.QTreeView(Config_Dialog)
        self.treeView.setGeometry(QtCore.QRect(110, 190, 181, 331))
        self.treeView.setObjectName("treeView")

        self.retranslateUi(Config_Dialog)
        self.buttonBox.accepted.connect(Config_Dialog.accept)
        self.buttonBox.rejected.connect(Config_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Config_Dialog)

    def retranslateUi(self, Config_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Config_Dialog.setWindowTitle(_translate("Config_Dialog", "实验配置"))
        self.pB_add1.setText(_translate("Config_Dialog", "添加"))
        self.pB_add2.setText(_translate("Config_Dialog", "添加"))
        self.pB_add3.setText(_translate("Config_Dialog", "添加"))
        self.label.setText(_translate("Config_Dialog", "实验菜单管理"))
        self.label_2.setText(_translate("Config_Dialog", "预处理算法管理"))
        self.label_3.setText(_translate("Config_Dialog", "单木定位算法管理"))
        self.label_4.setText(_translate("Config_Dialog", "实验配置"))
        self.pB_delete1.setText(_translate("Config_Dialog", "删除"))
        self.pB_delete2.setText(_translate("Config_Dialog", "删除"))
        self.pB_delete3.setText(_translate("Config_Dialog", "删除"))
