# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add_exp.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_exp_dialog(object):
    def setupUi(self, add_exp_dialog):
        add_exp_dialog.setObjectName("add_exp_dialog")
        add_exp_dialog.resize(709, 656)
        self.label_3 = QtWidgets.QLabel(add_exp_dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 40, 81, 16))
        self.label_3.setObjectName("label_3")
        self.para_type2 = QtWidgets.QLabel(add_exp_dialog)
        self.para_type2.setGeometry(QtCore.QRect(310, 410, 101, 16))
        self.para_type2.setObjectName("para_type2")
        self.para_type1 = QtWidgets.QLabel(add_exp_dialog)
        self.para_type1.setGeometry(QtCore.QRect(310, 370, 101, 16))
        self.para_type1.setObjectName("para_type1")
        self.pretreatment3 = QtWidgets.QComboBox(add_exp_dialog)
        self.pretreatment3.setGeometry(QtCore.QRect(330, 580, 101, 22))
        self.pretreatment3.setObjectName("pretreatment3")
        self.pretreatment4 = QtWidgets.QComboBox(add_exp_dialog)
        self.pretreatment4.setGeometry(QtCore.QRect(450, 580, 101, 22))
        self.pretreatment4.setObjectName("pretreatment4")
        self.Button_renew = QtWidgets.QPushButton(add_exp_dialog)
        self.Button_renew.setGeometry(QtCore.QRect(600, 40, 75, 23))
        self.Button_renew.setObjectName("Button_renew")
        self.label_4 = QtWidgets.QLabel(add_exp_dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 370, 101, 16))
        self.label_4.setObjectName("label_4")
        self.para2 = QtWidgets.QLineEdit(add_exp_dialog)
        self.para2.setGeometry(QtCore.QRect(430, 410, 113, 20))
        self.para2.setObjectName("para2")
        self.algorithm_select = QtWidgets.QComboBox(add_exp_dialog)
        self.algorithm_select.setGeometry(QtCore.QRect(140, 370, 131, 22))
        self.algorithm_select.setObjectName("algorithm_select")
        self.algorithm_select.addItem("")
        self.algorithm_select.addItem("")
        self.pretreatment2 = QtWidgets.QComboBox(add_exp_dialog)
        self.pretreatment2.setGeometry(QtCore.QRect(210, 580, 101, 22))
        self.pretreatment2.setObjectName("pretreatment2")
        self.para1 = QtWidgets.QLineEdit(add_exp_dialog)
        self.para1.setGeometry(QtCore.QRect(430, 370, 113, 20))
        self.para1.setObjectName("para1")
        self.pretreatment1 = QtWidgets.QComboBox(add_exp_dialog)
        self.pretreatment1.setGeometry(QtCore.QRect(90, 580, 101, 22))
        self.pretreatment1.setObjectName("pretreatment1")
        self.line_2 = QtWidgets.QFrame(add_exp_dialog)
        self.line_2.setGeometry(QtCore.QRect(40, 340, 631, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(add_exp_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(520, 490, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(add_exp_dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 70, 641, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_list = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_list.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_list.setObjectName("gridLayout_list")

        self.retranslateUi(add_exp_dialog)
        QtCore.QMetaObject.connectSlotsByName(add_exp_dialog)

    def retranslateUi(self, add_exp_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_exp_dialog.setWindowTitle(_translate("add_exp_dialog", "添加实验"))
        self.label_3.setText(_translate("add_exp_dialog", "预处理算法："))
        self.para_type2.setText(_translate("add_exp_dialog", "参数2 ："))
        self.para_type1.setText(_translate("add_exp_dialog", "参数1 ："))
        self.Button_renew.setText(_translate("add_exp_dialog", "重置"))
        self.label_4.setText(_translate("add_exp_dialog", "单木提取算法："))
        self.algorithm_select.setItemText(0, _translate("add_exp_dialog", "请选择"))
        self.algorithm_select.setItemText(1, _translate("add_exp_dialog", "CV算法"))
