# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'march.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MarchSetting(object):
    def setupUi(self, MarchSetting):
        MarchSetting.setObjectName("MarchSetting")
        MarchSetting.resize(799, 656)
        self.buttonBox = QtWidgets.QDialogButtonBox(MarchSetting)
        self.buttonBox.setGeometry(QtCore.QRect(390, 600, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(MarchSetting)
        self.label.setGeometry(QtCore.QRect(80, 110, 171, 41))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MarchSetting)
        self.label_2.setGeometry(QtCore.QRect(490, 110, 171, 41))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.listView_set = QtWidgets.QListView(MarchSetting)
        self.listView_set.setGeometry(QtCore.QRect(80, 170, 201, 351))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        self.listView_set.setFont(font)
        self.listView_set.setObjectName("listView_set")
        self.listView = QtWidgets.QListView(MarchSetting)
        self.listView.setGeometry(QtCore.QRect(490, 170, 201, 351))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        self.listView.setFont(font)
        self.listView.setObjectName("listView")
        self.label_3 = QtWidgets.QLabel(MarchSetting)
        self.label_3.setGeometry(QtCore.QRect(340, 40, 121, 31))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.addBT1 = QtWidgets.QPushButton(MarchSetting)
        self.addBT1.setGeometry(QtCore.QRect(120, 540, 75, 23))
        self.addBT1.setObjectName("addBT1")
        self.deleteBT1 = QtWidgets.QPushButton(MarchSetting)
        self.deleteBT1.setGeometry(QtCore.QRect(210, 540, 75, 23))
        self.deleteBT1.setObjectName("deleteBT1")
        self.deleteBT2 = QtWidgets.QPushButton(MarchSetting)
        self.deleteBT2.setGeometry(QtCore.QRect(620, 540, 75, 23))
        self.deleteBT2.setObjectName("deleteBT2")
        self.addBT2 = QtWidgets.QPushButton(MarchSetting)
        self.addBT2.setGeometry(QtCore.QRect(530, 540, 75, 23))
        self.addBT2.setObjectName("addBT2")

        self.retranslateUi(MarchSetting)
        self.buttonBox.accepted.connect(MarchSetting.accept)
        self.buttonBox.rejected.connect(MarchSetting.reject)
        QtCore.QMetaObject.connectSlotsByName(MarchSetting)

    def retranslateUi(self, MarchSetting):
        _translate = QtCore.QCoreApplication.translate
        MarchSetting.setWindowTitle(_translate("MarchSetting", "模板管理（模板匹配）"))
        self.label.setText(_translate("MarchSetting", "模板集合："))
        self.label_2.setText(_translate("MarchSetting", "集合内模板："))
        self.label_3.setText(_translate("MarchSetting", "模板管理"))
        self.addBT1.setText(_translate("MarchSetting", "添加"))
        self.deleteBT1.setText(_translate("MarchSetting", "删除"))
        self.deleteBT2.setText(_translate("MarchSetting", "删除"))
        self.addBT2.setText(_translate("MarchSetting", "添加"))
