# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Visual_mark.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Visual(object):
    def setupUi(self, Visual):
        Visual.setObjectName("Visual")
        Visual.resize(880, 535)
        self.img_widget = QtWidgets.QWidget(Visual)
        self.img_widget.setGeometry(QtCore.QRect(40, 100, 801, 391))
        self.img_widget.setObjectName("img_widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Visual)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 841, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.count = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(24)
        self.count.setFont(font)
        self.count.setObjectName("count")
        self.horizontalLayout.addWidget(self.count)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Revoke = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Revoke.setObjectName("Revoke")
        self.horizontalLayout.addWidget(self.Revoke)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.finish = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.finish.setObjectName("finish")
        self.horizontalLayout.addWidget(self.finish)
        self.save = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.save.setObjectName("save")
        self.horizontalLayout.addWidget(self.save)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)

        self.retranslateUi(Visual)
        QtCore.QMetaObject.connectSlotsByName(Visual)

    def retranslateUi(self, Visual):
        _translate = QtCore.QCoreApplication.translate
        Visual.setWindowTitle(_translate("Visual", "目视标记"))
        self.label_2.setText(_translate("Visual", "标记尺寸："))
        self.label.setText(_translate("Visual", "计数："))
        self.count.setText(_translate("Visual", "55"))
        self.Revoke.setText(_translate("Visual", "回退"))
        self.finish.setText(_translate("Visual", "完成"))
        self.save.setText(_translate("Visual", "保存"))
